.TH chaoban 1 "2019-01-10" "chaoban" chaoban
.SH NAME
.B chaoban 
\- In ra giữa màn hình dòng chữ 'Chao ban tên_bạn'
.SH SYNOPSIS
Nhập tên chương trình (lệnh)
.B chaoban 
sẽ có thông tin sau ở giữa màn hình
.br
Che do man hinh: x dong y cot
.br
Nhap ten ban: --> nhập tên bạn vào
.SH OPTIONS
Chương trình này không có tùy chọn
.SH DESRIPTION
Nhập tên tối đa 40 kí tự
