.TH chaoban 1 "2019-01-10" "chaoban" chaoban
.SH NAME
chaoban \- In ra giua man hinh dong chu 'Chao ban ten_ban'
.SH SYNOPSIS
Nhap ten chuong trinh (lenh) chaoban se co thong tin sau o giua man hinh
.br
Che do man hinh: x dong y cot
.br
Nhap ten ban: --> nhap ten ban vao
.SH OPTIONS
Chuong trinh nay khong co tuy chon
.SH DESRIPTION
Nhap ten toi da 40 ki tu
